### ISSUE TITLE
Documenting upstream issue

### ISSUE THREAD

**Issue by stuvet** [maximbaz/snap-pac-grub#6]
After upgrading `btrfs-progs` to `6.1.1` on `6.1.1-arch1-1` each `pacman -Su` triggers errors like:

```
[2022-12-27T16:22:30+0000] [ALPM-SCRIPTLET] grep: /tmp/grub-btrfs.lvdxefEBlJ//etc/fstab: No such file or directory
```
Downgrading `btrfs-progs` to `6.0.2-1` fixes this issue, allowing grub snapshots to complete as expected.

May be a downstream effect of https://github.com/kdave/btrfs-progs/issues/562#issue-1511403934

Feel free to close this as necessary, but I'll keep an eye on `btrfs-progs` & close after fixes are merged.

**Comment by max-baz** [comment]
Thanks, let's keep an eye on that bug 👍

**Comment by stuvet** [comment]
Everything seems to be working as expected with `btrfs-progs` `6.1-2`. Closing issue.
