### ISSUE TITLE
Please add ability to change snapshots from readonly to write

### ISSUE THREAD

**Issue by LDprg** [maximbaz/snap-pac-grub#7]
Please change snapshotsflag from readonly to write before updating grub menue so you can boot into the snapshots!

**Comment by max-baz** [comment]
It's quite possible to boot into readonly snapshots, moreover it's quite important to keep them readonly, as you might accidentally overwrite and destroy your last backup.

In any case I think your request belongs to `grub-btrfs` and not to this wrapper, and that project already has a lot of resources on both how to change to `rw` or how to fix boot in readonly snapshots (e.g. https://github.com/Antynea/grub-btrfs/issues/88#issuecomment-668715906)

**Comment by LDprg** [comment]
Oh, sorry for the issue at the wrong place.
