### ISSUE TITLE
Error when installing/updating (arch - yay)

### ISSUE THREAD

**Issue by smsjr** [maximbaz/snap-pac-grub#9]
After last update, I'm getting an error while updating package through yay:

```
...

==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'zz-snap-pac-grub-post.hook': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: snap-pac-grub-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
snap-pac-grub - exit status 4
```

Seems like the extra "z" in zz-snap-pac-grub-postZ.hook is the problem...

**Comment by max-baz** [comment]
Many thanks for report, my bad, could you try `2.0.3-2` that I just pushed to AUR ?

**Comment by smsjr** [comment]
Now works perfectly! Thanks a lot!!!

Att.,

JUNIOR SMS
***@***.***

________________________________________________________________________________

INFORMAÇÃO CONFIDENCIAL: Este email e seus anexos contém informações
confidenciais e qualquer uso, distribuição ou cópia não autorizada é
estritamente proibida. Se você recebeu esta mensagem indevidamente ou por
engano, por favor, informe ao remetente deste fato e apague-a de seu computador.
NOTICE: This e-mail message and attached files contain confidential information.
Any unauthorized, use, distribution or copy is prohibited. If you are not the
intended recipient, please contact the sender by reply e-mail and destroy all
copies of the original message.
________________________________________________________________________________
